//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_management
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public class_management()
        {
            this.attendances = new HashSet<attendance>();
            this.course_registration = new HashSet<course_registration>();
        }
    
        public int class_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> class_instructor_id { get; set; }
        public string class_name { get; set; }
        public Nullable<System.DateTime> class_start_date { get; set; }
        public Nullable<System.DateTime> class_end_date { get; set; }
        public Nullable<int> max_seats { get; set; }
        public Nullable<int> available_seats { get; set; }
        public string is_registration_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        public virtual instructor instructor { get; set; }
        public virtual course_management course_management { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_registration> course_registration { get; set; }
    }
}
