//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company_employee()
        {
            this.attendances = new HashSet<attendance>();
            this.course_registration = new HashSet<course_registration>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_full_name { get; set; }
        public string user_title { get; set; }
        public string user_department { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public string is_admin { get; set; }
        public string is_manager { get; set; }
        public string is_instructor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        public virtual manager manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_registration> course_registration { get; set; }
    }
}
